ALTER TABLE "Airline" ADD COLUMN IF NOT EXISTS "legalName" TEXT;
ALTER TABLE "Airline" ADD COLUMN IF NOT EXISTS "correspondenceAddress" TEXT;
ALTER TABLE "Airline" ADD COLUMN IF NOT EXISTS "addressLine" TEXT;
ALTER TABLE "Airline" ADD COLUMN IF NOT EXISTS "postalCode" TEXT;
ALTER TABLE "Airline" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Airline" ADD COLUMN IF NOT EXISTS "registryInfo" TEXT;
ALTER TABLE "Airline" ADD COLUMN IF NOT EXISTS "complaintEmail" TEXT;
