export type AirlineCrmData = {
  iata: string;
  name: string;
  legalName: string;
  aliases?: readonly string[];
  correspondenceAddress: string;
  addressLine: string;
  postalCode: string;
  city: string;
  country: string;
  registryInfo: string;
  complaintEmail?: string;
  operationalNotes?: string;
};

export const airlineCrmData: readonly AirlineCrmData[] = [
  {
    iata: "LO",
    name: "Polskie Linie Lotnicze LOT S.A.",
    legalName: "Polskie Linie Lotnicze LOT S.A.",
    aliases: ["LOT", "LOT Polish Airlines"],
    correspondenceAddress:
      "ul. Komitetu Obrony Robotników 43, 02-146 Warszawa, Polska",
    addressLine: "ul. Komitetu Obrony Robotników 43",
    postalCode: "02-146",
    city: "Warszawa",
    country: "Polska",
    registryInfo: "KRS: 0000056844",
  },
  {
    iata: "FR",
    name: "Ryanair DAC",
    legalName: "Ryanair DAC",
    aliases: ["Ryanair"],
    correspondenceAddress: "Airside Business Park, Swords, Co. Dublin, Irlandia",
    addressLine: "Airside Business Park",
    postalCode: "",
    city: "Swords, Co. Dublin",
    country: "Irlandia",
    registryInfo: "Irish CRO: 104547",
  },
  {
    iata: "W6",
    name: "Wizz Air Hungary Ltd.",
    legalName: "Wizz Air Hungary Ltd.",
    aliases: ["Wizz Air"],
    correspondenceAddress: "Lechner Ödön fasor 6, 1095 Budapest, Węgry",
    addressLine: "Lechner Ödön fasor 6",
    postalCode: "1095",
    city: "Budapest",
    country: "Węgry",
    registryInfo: "Hungary Reg.: 01-10-140174",
  },
  {
    iata: "LH",
    name: "Deutsche Lufthansa AG",
    legalName: "Deutsche Lufthansa AG",
    aliases: ["Lufthansa"],
    correspondenceAddress: "Venloer Straße 151-153, 50672 Köln, Niemcy",
    addressLine: "Venloer Straße 151-153",
    postalCode: "50672",
    city: "Köln",
    country: "Niemcy",
    registryInfo: "Handelsregister Köln: HRB 2168",
  },
  {
    iata: "EW",
    name: "Eurowings GmbH",
    legalName: "Eurowings GmbH",
    aliases: ["Eurowings"],
    correspondenceAddress: "Waldstraße 249, 51147 Köln, Niemcy",
    addressLine: "Waldstraße 249",
    postalCode: "51147",
    city: "Köln",
    country: "Niemcy",
    registryInfo: "Handelsregister Düsseldorf: HRB 66807",
  },
  {
    iata: "AF",
    name: "Air France",
    legalName: "Air France",
    correspondenceAddress: "45 Rue de Paris, 95747 Roissy CDG Cedex, Francja",
    addressLine: "45 Rue de Paris",
    postalCode: "95747",
    city: "Roissy CDG Cedex",
    country: "Francja",
    registryInfo: "RCS Bobigny: 420 495 178",
  },
  {
    iata: "KL",
    name: "KLM Royal Dutch Airlines",
    legalName: "KLM Royal Dutch Airlines",
    aliases: ["KLM"],
    correspondenceAddress:
      "Amsterdamseweg 55, 1182 GP Amstelveen, Holandia",
    addressLine: "Amsterdamseweg 55",
    postalCode: "1182 GP",
    city: "Amstelveen",
    country: "Holandia",
    registryInfo: "KvK: 33014286",
  },
  {
    iata: "BA",
    name: "British Airways plc",
    legalName: "British Airways plc",
    aliases: ["British Airways"],
    correspondenceAddress:
      "Waterside, PO Box 365, Harmondsworth UB7 0GB, Wielka Brytania",
    addressLine: "Waterside, PO Box 365",
    postalCode: "UB7 0GB",
    city: "Harmondsworth",
    country: "Wielka Brytania",
    registryInfo: "Companies House: 01777777",
  },
  {
    iata: "IB",
    name: "Iberia Líneas Aéreas de España S.A.",
    legalName: "Iberia Líneas Aéreas de España S.A.",
    aliases: ["Iberia"],
    correspondenceAddress:
      "Calle Martínez Villergas 49, 28027 Madrid, Hiszpania",
    addressLine: "Calle Martínez Villergas 49",
    postalCode: "28027",
    city: "Madrid",
    country: "Hiszpania",
    registryInfo: "CIF: A85850394",
  },
  {
    iata: "VY",
    name: "Vueling Airlines S.A.",
    legalName: "Vueling Airlines S.A.",
    aliases: ["Vueling"],
    correspondenceAddress: "Viladecans Business Park, Catalunya, Hiszpania",
    addressLine: "Viladecans Business Park",
    postalCode: "",
    city: "Catalunya",
    country: "Hiszpania",
    registryInfo: "CIF: A63422141",
  },
  {
    iata: "TP",
    name: "TAP Air Portugal",
    legalName: "TAP Air Portugal",
    correspondenceAddress:
      "Edifício 25, Aeroporto de Lisboa, 1704-801 Lisboa, Portugalia",
    addressLine: "Edifício 25, Aeroporto de Lisboa",
    postalCode: "1704-801",
    city: "Lisboa",
    country: "Portugalia",
    registryInfo: "NIPC: 500278725",
  },
  {
    iata: "AZ",
    name: "ITA Airways S.p.A.",
    legalName: "ITA Airways S.p.A.",
    aliases: ["ITA Airways"],
    correspondenceAddress: "Via XX Settembre 97, 00187 Roma, Włochy",
    addressLine: "Via XX Settembre 97",
    postalCode: "00187",
    city: "Roma",
    country: "Włochy",
    registryInfo: "Registro Imprese: 15907661001",
  },
  {
    iata: "SN",
    name: "Brussels Airlines NV/SA",
    legalName: "Brussels Airlines NV/SA",
    aliases: ["Brussels Airlines"],
    correspondenceAddress: "b.house Airport Building 26, 1831 Diegem, Belgia",
    addressLine: "b.house Airport Building 26",
    postalCode: "1831",
    city: "Diegem",
    country: "Belgia",
    registryInfo: "BCE/KBO: 0443229056",
  },
  {
    iata: "OS",
    name: "Austrian Airlines AG",
    legalName: "Austrian Airlines AG",
    aliases: ["Austrian Airlines"],
    correspondenceAddress:
      "Office Park 2, Postfach 100, 1300 Wien-Flughafen, Austria",
    addressLine: "Office Park 2, Postfach 100",
    postalCode: "1300",
    city: "Wien-Flughafen",
    country: "Austria",
    registryInfo: "FN 111000z",
  },
  {
    iata: "LX",
    name: "Swiss International Air Lines AG",
    legalName: "Swiss International Air Lines AG",
    aliases: ["Swiss"],
    correspondenceAddress: "Zürich Airport, 8058 Zürich-Flughafen, Szwajcaria",
    addressLine: "Zürich Airport",
    postalCode: "8058",
    city: "Zürich-Flughafen",
    country: "Szwajcaria",
    registryInfo: "CHE-105.923.968",
  },
  {
    iata: "SK",
    name: "Scandinavian Airlines System Denmark-Norway-Sweden",
    legalName: "Scandinavian Airlines System Denmark-Norway-Sweden",
    aliases: ["SAS", "SAS Scandinavian Airlines"],
    correspondenceAddress:
      "Frösundaviks Allé 1, 195 87 Stockholm, Szwecja",
    addressLine: "Frösundaviks Allé 1",
    postalCode: "195 87",
    city: "Stockholm",
    country: "Szwecja",
    registryInfo: "Swedish Org.nr: 902001-7720",
  },
  {
    iata: "DY",
    name: "Norwegian Air Shuttle ASA",
    legalName: "Norwegian Air Shuttle ASA",
    aliases: ["Norwegian"],
    correspondenceAddress: "Oksenøyveien 3, 1366 Lysaker, Norwegia",
    addressLine: "Oksenøyveien 3",
    postalCode: "1366",
    city: "Lysaker",
    country: "Norwegia",
    registryInfo: "Org.nr: 965920358",
  },
  {
    iata: "BT",
    name: "airBaltic Corporation AS",
    legalName: "airBaltic Corporation AS",
    aliases: ["airBaltic"],
    correspondenceAddress: "Tehnikas iela 3, Riga LV-1053, Łotwa",
    addressLine: "Tehnikas iela 3",
    postalCode: "LV-1053",
    city: "Riga",
    country: "Łotwa",
    registryInfo: "Reg.nr: 40003245752",
  },
  {
    iata: "AY",
    name: "Finnair Oyj",
    legalName: "Finnair Oyj",
    aliases: ["Finnair"],
    correspondenceAddress: "Tietotie 9, 01530 Vantaa, Finlandia",
    addressLine: "Tietotie 9",
    postalCode: "01530",
    city: "Vantaa",
    country: "Finlandia",
    registryInfo: "Business ID: 0108023-3",
  },
  {
    iata: "RO",
    name: "TAROM S.A.",
    legalName: "TAROM S.A.",
    aliases: ["TAROM"],
    correspondenceAddress: "Calea Bucureștilor 224F, Otopeni, Rumunia",
    addressLine: "Calea Bucureștilor 224F",
    postalCode: "",
    city: "Otopeni",
    country: "Rumunia",
    registryInfo: "J40/23778/1991",
  },
  {
    iata: "OU",
    name: "Croatia Airlines d.d.",
    legalName: "Croatia Airlines d.d.",
    aliases: ["Croatia Airlines"],
    correspondenceAddress: "Bani 75B, Buzin, 10010 Zagreb, Chorwacja",
    addressLine: "Bani 75B, Buzin",
    postalCode: "10010",
    city: "Zagreb",
    country: "Chorwacja",
    registryInfo: "MBS: 080010698",
  },
  {
    iata: "A3",
    name: "Aegean Airlines S.A.",
    legalName: "Aegean Airlines S.A.",
    aliases: ["Aegean Airlines"],
    correspondenceAddress:
      "31 Viltanioti Street, 14564 Kifissia, Ateny, Grecja",
    addressLine: "31 Viltanioti Street",
    postalCode: "14564",
    city: "Kifissia, Ateny",
    country: "Grecja",
    registryInfo: "GEMI: 1796601000",
  },
  {
    iata: "EI",
    name: "Aer Lingus Limited",
    legalName: "Aer Lingus Limited",
    aliases: ["Aer Lingus"],
    correspondenceAddress: "Dublin Airport, Dublin, Irlandia",
    addressLine: "Dublin Airport",
    postalCode: "",
    city: "Dublin",
    country: "Irlandia",
    registryInfo: "Irish CRO: 5316",
  },
  {
    iata: "KM",
    name: "KM Malta Airlines Ltd",
    legalName: "KM Malta Airlines Ltd",
    aliases: ["KM Malta Airlines"],
    correspondenceAddress:
      "SkyParks Business Centre, Luqa LQA 4000, Malta",
    addressLine: "SkyParks Business Centre",
    postalCode: "LQA 4000",
    city: "Luqa",
    country: "Malta",
    registryInfo: "Malta C Number: C104823",
  },
  {
    iata: "LG",
    name: "Luxair S.A.",
    legalName: "Luxair S.A.",
    aliases: ["Luxair"],
    correspondenceAddress: "Aéroport de Luxembourg, L-2987 Luxembourg",
    addressLine: "Aéroport de Luxembourg",
    postalCode: "L-2987",
    city: "Luxembourg",
    country: "Luxembourg",
    registryInfo: "RCS Luxembourg: B4109",
  },
  {
    iata: "JU",
    name: "Air Serbia a.d.",
    legalName: "Air Serbia a.d.",
    aliases: ["Air Serbia"],
    correspondenceAddress: "Jurija Gagarina 12, 11070 Belgrade, Serbia",
    addressLine: "Jurija Gagarina 12",
    postalCode: "11070",
    city: "Belgrade",
    country: "Serbia",
    registryInfo: "Serbian Reg.: 20044448",
  },
  {
    iata: "PC",
    name: "Pegasus Hava Taşımacılığı A.Ş.",
    legalName: "Pegasus Hava Taşımacılığı A.Ş.",
    aliases: ["Pegasus"],
    correspondenceAddress:
      "Aeropark, Yenişehir Mah., Kurtköy, Istanbul, Turcja",
    addressLine: "Aeropark, Yenişehir Mah., Kurtköy",
    postalCode: "",
    city: "Istanbul",
    country: "Turcja",
    registryInfo: "MERSIS: 0720034283000015",
  },
  {
    iata: "TK",
    name: "Türk Hava Yolları A.O.",
    legalName: "Türk Hava Yolları A.O.",
    aliases: ["Turkish Airlines"],
    correspondenceAddress: "Atatürk Airport, Yesilkoy, Istanbul, Turcja",
    addressLine: "Atatürk Airport, Yesilkoy",
    postalCode: "",
    city: "Istanbul",
    country: "Turcja",
    registryInfo: "MERSIS: 0876005220500017",
  },
  {
    iata: "LS",
    name: "Jet2.com Limited",
    legalName: "Jet2.com Limited",
    aliases: ["Jet2"],
    correspondenceAddress:
      "Low Fare Finder House, Leeds Bradford Airport, Leeds LS19 7TU, UK",
    addressLine: "Low Fare Finder House, Leeds Bradford Airport",
    postalCode: "LS19 7TU",
    city: "Leeds",
    country: "Wielka Brytania",
    registryInfo: "Companies House: 03959649",
  },
  {
    iata: "DE",
    name: "Condor Flugdienst GmbH",
    legalName: "Condor Flugdienst GmbH",
    aliases: ["Condor"],
    correspondenceAddress:
      "An der Gehespitz 50, 63263 Neu-Isenburg, Niemcy",
    addressLine: "An der Gehespitz 50",
    postalCode: "63263",
    city: "Neu-Isenburg",
    country: "Niemcy",
    registryInfo: "HRB 95558",
  },
  {
    iata: "RR",
    name: "Buzz Airlines DAC Oddział w Polsce",
    legalName: "Buzz Airlines DAC Oddział w Polsce",
    aliases: ["Buzz"],
    correspondenceAddress: "ul. Cybernetyki 21, 02-677 Warszawa, Polska",
    addressLine: "ul. Cybernetyki 21",
    postalCode: "02-677",
    city: "Warszawa",
    country: "Polska",
    registryInfo: "KRS: 0000409151",
  },
  {
    iata: "E4",
    name: "Enter Air Sp. z o.o.",
    legalName: "Enter Air Sp. z o.o.",
    aliases: ["Enter Air"],
    correspondenceAddress: "ul. Bokserska 66, 02-690 Warszawa, Polska",
    addressLine: "ul. Bokserska 66",
    postalCode: "02-690",
    city: "Warszawa",
    country: "Polska",
    registryInfo: "KRS: 0000339408; NIP: PL7010206959",
    operationalNotes:
      "Arkusz zawiera też wpis Enter Air S.A. dla kodu E4: KRS: 0000441533; NIP: 5272687350; REGON: 146414470.",
  },
] as const;

export function getAirlineCrmDataByIata(
  iata: string | null | undefined,
): AirlineCrmData | null {
  const normalized = iata?.trim().toUpperCase();

  return normalized
    ? (airlineCrmData.find((airline) => airline.iata === normalized) ?? null)
    : null;
}
