import type { UserRole } from "@prisma/client";

export const PERMISSIONS = {
  CLAIM_CREATE: "CLAIM_CREATE",
  CLAIM_READ_ALL: "CLAIM_READ_ALL",
  CLAIM_READ_OWN: "CLAIM_READ_OWN",
  CLAIM_EDIT: "CLAIM_EDIT",
  CLAIM_CHANGE_STATUS: "CLAIM_CHANGE_STATUS",
  CLAIM_CHANGE_COMMISSION: "CLAIM_CHANGE_COMMISSION",
  CLAIM_ASSIGN_OWNER: "CLAIM_ASSIGN_OWNER",
  CLAIM_DELETE: "CLAIM_DELETE",
  CLIENT_READ: "CLIENT_READ",
  CLIENT_EDIT: "CLIENT_EDIT",
  CLIENT_ANONYMIZE: "CLIENT_ANONYMIZE",
  DOCUMENT_GENERATE: "DOCUMENT_GENERATE",
  DOCUMENT_DOWNLOAD: "DOCUMENT_DOWNLOAD",
  DOCUMENT_EDIT_TEMPLATES: "DOCUMENT_EDIT_TEMPLATES",
  ATTACHMENT_UPLOAD: "ATTACHMENT_UPLOAD",
  ATTACHMENT_VIEW: "ATTACHMENT_VIEW",
  ATTACHMENT_DELETE: "ATTACHMENT_DELETE",
  NOTE_CREATE: "NOTE_CREATE",
  NOTE_VIEW: "NOTE_VIEW",
  TASK_CREATE: "TASK_CREATE",
  TASK_ASSIGN: "TASK_ASSIGN",
  TASK_CLOSE: "TASK_CLOSE",
  REPORT_SALES: "REPORT_SALES",
  REPORT_OPERATIONAL: "REPORT_OPERATIONAL",
  REPORT_FINANCIAL: "REPORT_FINANCIAL",
  REPORT_MARKETING: "REPORT_MARKETING",
  PAYOUT_VIEW: "PAYOUT_VIEW",
  PAYOUT_ENTER: "PAYOUT_ENTER",
  PAYOUT_APPROVE: "PAYOUT_APPROVE",
  ADMIN_USERS: "ADMIN_USERS",
  ADMIN_STATUS_CONFIG: "ADMIN_STATUS_CONFIG",
  ADMIN_AUDIT_LOG: "ADMIN_AUDIT_LOG",
  ADMIN_EXPORT: "ADMIN_EXPORT",
  BLOG_MANAGE: "BLOG_MANAGE",
  NEWSLETTER_MANAGE: "NEWSLETTER_MANAGE",
  BILLING_EDIT: "BILLING_EDIT",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const allPermissions = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  ADMIN: allPermissions,
  EDITOR: [
    PERMISSIONS.BLOG_MANAGE,
    PERMISSIONS.NEWSLETTER_MANAGE,
    PERMISSIONS.BILLING_EDIT,
  ],
  OPERATOR: [
    PERMISSIONS.CLAIM_CREATE,
    PERMISSIONS.CLAIM_READ_ALL,
    PERMISSIONS.CLAIM_READ_OWN,
    PERMISSIONS.CLAIM_EDIT,
    PERMISSIONS.CLAIM_CHANGE_STATUS,
    PERMISSIONS.CLAIM_ASSIGN_OWNER,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CLIENT_EDIT,
    PERMISSIONS.DOCUMENT_GENERATE,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.ATTACHMENT_VIEW,
    PERMISSIONS.ATTACHMENT_DELETE,
    PERMISSIONS.NOTE_CREATE,
    PERMISSIONS.NOTE_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_CLOSE,
    PERMISSIONS.REPORT_SALES,
  ],
  LAWYER: [
    PERMISSIONS.CLAIM_READ_ALL,
    PERMISSIONS.CLAIM_READ_OWN,
    PERMISSIONS.CLAIM_EDIT,
    PERMISSIONS.CLAIM_CHANGE_STATUS,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.DOCUMENT_GENERATE,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.ATTACHMENT_VIEW,
    PERMISSIONS.NOTE_CREATE,
    PERMISSIONS.NOTE_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_CLOSE,
  ],
  MARKETING: [
    PERMISSIONS.CLAIM_READ_ALL,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.REPORT_SALES,
    PERMISSIONS.REPORT_MARKETING,
    PERMISSIONS.NEWSLETTER_MANAGE,
  ],
  READ_ONLY: [
    PERMISSIONS.CLAIM_READ_ALL,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.ATTACHMENT_VIEW,
    PERMISSIONS.NOTE_VIEW,
    PERMISSIONS.REPORT_SALES,
    PERMISSIONS.REPORT_OPERATIONAL,
    PERMISSIONS.REPORT_FINANCIAL,
    PERMISSIONS.REPORT_MARKETING,
    PERMISSIONS.PAYOUT_VIEW,
  ],
};

export function hasRolePermission(role: UserRole, permission: Permission) {
  return ROLE_PERMISSIONS[role].includes(permission);
}

export function canLawyerSetClaimStatus(status: string) {
  return [
    "COURT_DECISION_PENDING",
    "COURT_STAGE",
    "WON",
    "SETTLEMENT",
    "DISMISSED",
  ].includes(status);
}
